---

# the preferences of dnf-automatic are documented at
# https://dnf.readthedocs.org/en/latest/automatic.html

# [commands]

dnf_automatic_apply_updates: true
dnf_automatic_download_updates: true
dnf_automatic_upgrade_type: security
dnf_automatic_random_sleep: 300

# [emitters]

dnf_automatic_emit_via: stdio
dnf_automatic_system_name: "{{ ansible_nodename }}"

# [command]

dnf_automatic_command_format: cat
dnf_automatic_stdin_format: "{body}"

# [command_email]

dnf_automatic_email_command_format: "mail -s {subject} -r {email_from} {email_to}"
dnf_automatic_email_stdin_format: "{body}"

# [email]

dnf_automatic_email_from: root
dnf_automatic_email_to: root
dnf_automatic_email_host: localhost

# [base]

# this dict can be used to override arbitrary settings from dnf.conf
dnf_automatic_base_overrides: {}

# Reboot

dnf_automatic_reboot: false
dnf_automatic_reboot_dependencies: yum-utils
dnf_automatic_reboot_OnCalendar: "03:00"
dnf_automatic_reboot_AccuracySec: "15s"
dnf_automatic_reboot_Description: "dnf-automatic-reboot"
dnf_automatic_reboot_ExecStart: "/bin/bash -c '/bin/needs-restarting -r || /sbin/reboot'"
