---
- name: Converge
  hosts: all

  tasks:
    - name: "Include ansible-role-dnf-automatic"
      ansible.builtin.include_role:
        name: "ansible-role-dnf-automatic"
      vars:
        dnf_automatic_reboot: true
