name = "sap"
description = "Custom RHEL 9 image with SAP configuration"
version = "0.0.1"
distro = "rhel-9"

# SAP package set
# https://github.com/osbuild/images/blob/64d9a460b558e0751df4a9b1032acf02588fda97/pkg/distro/rhel9/sap.go#L121
packages = [
    { name = "@Server" },
    { name = "ansible-core" },
    { name = "rhel-system-roles-sap" },
    { name = "bind-utils" },
    { name = "nfs-utils" },
    { name = "tcsh" },
    { name = "uuidd" },
    { name = "cairo" },
    { name = "expect" },
    { name = "graphviz" },
    { name = "gtk2" },
    { name = "iptraf-ng" },
    { name = "krb5-workstation" },
    { name = "libaio" },
    { name = "libatomic" },
    { name = "libcanberra-gtk2" },
    { name = "libicu" },
    { name = "libtool-ltdl" },
    { name = "lm_sensors" },
    { name = "net-tools" },
    { name = "numactl" },
    { name = "PackageKit-gtk3-module" },
    { name = "xorg-x11-xauth" },
    { name = "tuned-profiles-sap-hana" },
    { name = "libnsl" }
]

[customizations]
hostname = "sap"

##########################################################################################################################
# SAP CONFIGURATION                                                                                                      #
# Taken from https://github.com/osbuild/images/blob/64d9a460b558e0751df4a9b1032acf02588fda97/pkg/distro/rhel9/sap.go#L10 #
##########################################################################################################################

# https://github.com/osbuild/images/blob/64d9a460b558e0751df4a9b1032acf02588fda97/pkg/distro/rhel9/ami.go#L114
[customizations.kernel]
append = "processor.max_cstate=1 intel_idle.max_cstate=1"

# Set SELinux to permissive mode
[[customizations.files]]
path = "/etc/selinux/config"
data = """
SELINUX=permissive
SELINUXTYPE=targeted
"""

# Set the default tuned profile to sap-hana
[[customizations.files]]
path = "/etc/tuned/active_profile"
data = """
sap-hana
"""

# Mode needs to be set to "manual" if tuned profile is set explicitly
[[customizations.files]]
path = "/etc/tuned/profile_mode"
data = """
manual
"""

# tmpfiles.d configuration
[[customizations.files]]
path = "/etc/tmpfiles.d/sap.conf"
data = """
x /tmp/.sap*
x /tmp/.hdb*lock
x /tmp/.trex*lock
"""

# PAM limits configuration
[[customizations.files]]
path = "/etc/security/limits.d/99-sap.conf"
data = """
@sapsys    hard    nofile   1048576
@sapsys    soft    nofile   1048576
@dba       hard    nofile   1048576
@dba       soft    nofile   1048576
@sapsys    hard    nproc    unlimited
@sapsys    soft    nproc    unlimited
@dba       hard    nproc    unlimited
@dba       soft    nproc    unlimited
"""

# Sysctl configuration
[[customizations.files]]
path = "/etc/sysctl.d/sap.conf"
data = """
kernel.pid_max = 4194304
vm.max_map_count = 2147483647
"""

# Set the release version to 9.2 in DNF configutation
[[customizations.files]]
path = "/etc/dnf/vars/releasever"
data = """
9.2
"""

# Create a custom service unit, which will remove unwanted packages,
# since there is no way to exclude packages from package groups.
# https://github.com/osbuild/images/blob/64d9a460b558e0751df4a9b1032acf02588fda97/pkg/distro/rhel9/sap.go#L158
[[customizations.files]]
path = "/etc/systemd/system/custom-first-boot.service"
data = """
[Unit]
Description=Custom first boot service
ConditionPathExists=/etc/custom-first-boot

[Service]
Type=oneshot

# As the first thing, ensure that the service will not run again
ExecStart=/usr/bin/rm /etc/custom-first-boot
ExecStart=/usr/bin/dnf -y remove \
    firewalld \
    iwl1000-firmware \
    iwl100-firmware \
    iwl105-firmware \
    iwl135-firmware \
    iwl2000-firmware \
    iwl2030-firmware \
    iwl3160-firmware \
    iwl5000-firmware \
    iwl5150-firmware \
    iwl6000g2a-firmware \
    iwl6000g2b-firmware \
    iwl6050-firmware \
    iwl7260-firmware

[Install]
WantedBy=multi-user.target
"""

# Touch a file, which will ensure that the custom first boot service will run if enabled
[[customizations.files]]
path = "/etc/custom-first-boot"

# Enable the custom service
[customizations.services]
enabled = ["custom-first-boot"]

# @Server package group pulls in NetworkManager-config-server, which disables
# network interface auto-configuration. Therefore we need to explicitly create
# the network configuration file.
[[customizations.files]]
path = "/etc/sysconfig/network-scripts/ifcfg-eth0"
data = """
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
USERCTL="yes"
PEERDNS="yes"
IPV6INIT="no"
"""
